### ISSUE TITLE
Doesn't work for any site that requires basic HTTP authentication

### ISSUE THREAD

**Issue by ronenmagid** [romanlex/app-manifest-webpack-plugin#10]
The manifest is never generated with  `crossorigin="use-credentials" `thus will always get 401 error = doesn't work on any site requiring basic HTTP authentication.  As far as I see there is no way to configure this package to produce the required property to avoid this fatal error.

**Comment by romanlex** [comment]
@ronenmagid I'm so sorry for long reply
Now in your output you can see
```
<link rel="manifest" href="/manifest.json" crossOrigin="use-credentials">
```
by default 

https://www.npmjs.com/package/app-manifest-webpack-plugin/v/1.2.2
