### ISSUE TITLE
name, short_name, and scope

### ISSUE THREAD

**Issue by mkvlrn-cm42** [romanlex/app-manifest-webpack-plugin#2]
In the configuration object, what's `appName` exactly? Will it become `name` and `short_name` in the manifest?

Also, is there a chance to add `scope` as part of the configuration? I think it's the only setting not present that is necessary for a Progressive Web App manifest.

**Comment by aminnairi** [comment]
Yes, the `appName` is responsible for both the `name` and `short_name`, which is kind of weird in my opinion.

This would be awesome to have a support for the following properties for the Web Manifest:
- `dir`
- `lang`
- `short_name`
- `lang`
- `scope`

Following [Mozilla's Web Manifest documentation](https://developer.mozilla.org/en-US/docs/Web/Manifest).
