### ISSUE TITLE
Manifest.json and yandex-browser-manifest.json being injected but both not created

### ISSUE THREAD

**Issue by ghost** [romanlex/app-manifest-webpack-plugin#4]
A manifest.json file is injected into the HTML file, but it doesn't appear to be created. Is there any option I'm currently missing?

It is due to a couple of code snippets as follow:

```javascript
const webpackConfig = {
	plugins: [
	    new ScriptExtHtmlWebpackPlugin({
	        inline: /manifest/
	    }),
	    new AppManifestWebpackPlugin({
	        logo: 'my-logo.png'
	    })
	]
}
```

**Comment by romanlex** [comment]
I think it's because you use ScriptExtHtmlWebpackPlugin
manifest file removed from webpack assets and insert inlined into your html file
